### ISSUE TITLE
Add re2 to CQL

### ISSUE THREAD

**Issue by ngawangtrinley** [Esukhia/pybo#10]
At the moment CQL allows 3 wilcards on attributes: != & |
[text!="hello" & pos="NOUN|VERB"]

**Comment by eroux** [comment]
can you give an [mcve](https://stackoverflow.com/help/mcve)?

**Comment by drupchen** [comment]
Sorry for taking so long. Here it is at last:

```
test = [{'word': 'This',
         'lemma': True,
         'tag': 'Det'},
        {'word': 'is',
         'lemma': 'be',
         'tag': 0}]
q = '[lemma="this"] [tag!="ADJ"]'

matcher = CQLMatcher(q)
matched = matcher.match(test)
```

gives the following error: 

```
Traceback (most recent call last):
  File "/home/drupchen/PycharmProjects/Pybo/usage.py", line 12, in <module>
    matched = matcher.match(test)
  File "/home/drupchen/PycharmProjects/Pybo/pybo/cqlmatcher.py", line 28, in match
    if i + slice_len <= len(tokens_list) and self.query(tokens_list[i:i + slice_len + 1]):
  File "/home/drupchen/PycharmProjects/Pybo/pybo/third_party/cql.py", line 263, in __call__
    return list(nfa.find(tokens,debug))
  File "/home/drupchen/PycharmProjects/Pybo/pybo/third_party/fsa.py", line 98, in find
    for length in self.run(sequence[i:], False, debug):
  File "/home/drupchen/PycharmProjects/Pybo/pybo/third_party/fsa.py", line 70, in run
    if matchfunction(value):
  File "/home/drupchen/PycharmProjects/Pybo/pybo/third_party/cql.py", line 211, in match
    match = (expr.match(value[annottype]) is not None)
TypeError: expected string or bytes-like object
```

**Comment by mikkokotila** [comment]
> It's an issue since it stops us from matching all our Token attributes

@ngawangtrinley can you highlight why that is an issue i.e. why must we be able to do it?

**Comment by ngawangtrinley** [comment]
@mikkokotila I completely forgot the use case! I'll try to find some time tomorrow to have a closer look
